# Standard compiler variables
CC = g++
CCFLAGS = -std=c++14 -Wall -pedantic -g

# Rules start here
z1901330-project4: z1901330_project4.cc
	$(CC) $(CCFLAGS) -o z1901330_project4 z1901330_project4.cc -lpthread

clean:
	rm -f z1901330_project4