# Standard compiler variables
CC = g++
CCFLAGS = -std=c++14 -Wall -pedantic -g

# Rules start here
z1901330-project1: z1901330_project1.cc
	$(CC) $(CCFLAGS) -o z1901330_project1 z1901330_project1.cc

clean:
	rm -f z1901330_project1